# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd34da5e672c363866986dd209362235dc83e33fd8e0db34431452ab3b42687c01876efc605473fd09931c1658e43735005df2cb00882c0235c7b5f669fdbcc

test:
  secret_key_base: eafbb69ac4aa539f37af33e626d15440f39b77969b61baa59cf914801860c8ffea0b8bbe9191b8aff7475167d46c371b3d6c900b4a4c5b84dd1d764cbec01324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
